### ISSUE TITLE
Path of the result and input directories

### ISSUE THREAD

**Issue by abulenciamiguel** [lanadelrea/Katmon#7]
Should you opt to use relative path, you can add `${PWD}/` on [line27](https://github.com/lanadelrea/CoPi/blob/2d265eebfcda2ba10151ea3b70ef7b98bf94891e/modules/02-bammix.nf#L27) and [line49](https://github.com/lanadelrea/CoPi/blob/2d265eebfcda2ba10151ea3b70ef7b98bf94891e/modules/02-bammix.nf#L49).

For example, `bammix.py ${nextclade_tsv} ${PWD}/${params.in_dir}`

```
N E X T F L O W  ~  version 23.04.1
Launching `CoPi/main.nf` [modest_volta] DSL2 - revision: 9a59f5b6be
executor >  local (15)
[4a/013296] process > concat (Concatenating fasta files into all_sequences.fasta)            [100%] 1 of 1, cached: 1 ✔
executor >  local (16)
[4a/013296] process > concat (Concatenating fasta files into all_sequences.fasta)            [100%] 1 of 1, cached: 1 ✔
executor >  local (16)
[4a/013296] process > concat (Concatenating fasta files into all_sequences.fasta)            [100%] 1 of 1, cached: 1 ✔
executor >  local (16)
[4a/013296] process > concat (Concatenating fasta files into all_sequences.fasta)            [100%] 1 of 1, cached: 1 ✔
[a3/458da6] process > pangolin (Lineage assignment using pangolin tool)                      [  0%] 0 of 1
[58/f0accd] process > nextclade (Lineage assignment using nextclade)                         [100%] 1 of 1 ✔
[-        ] process > lineage_assignment                                                     -
[02/c570f3] process > bammix (Looking for positions with nucleotide mixtures using bammix)   [  0%] 0 of 3
[-        ] process > bam_filter                                                             -
[82/9fb2c5] process > virstrain (Identifying lineage assignment for barcode07 using Virst... [100%] 3 of 3 ✔
[72/81d6a3] process > freyja (Identifying relative lineage abundances of samples to see p... [100%] 3 of 3 ✔
[26/8cbcae] process > freyja_demix (Identifying relative lineage abundances of sample bar... [100%] 3 of 3 ✔
[33/f168f1] process > freyja_aggregate (Aggregating Freyja demix results)                    [100%] 1 of 1 ✔
[0b/4921f0] process > freyja_plot (Plotting relative lineage abundances of samples)          [100%] 1 of 1 ✔
[-        ] process > makevcf                                                                -
[-        ] process > bammixplot                                                             -
[-        ] process > aafplot_mutations                                                      -
[-        ] process > aafplot_amplicons                                                      -
[-        ] process > ampliconsorting_DeltaReads                                             -
[-        ] process > ampliconsorting_OmicronReads                                           -
[-        ] process > ampliconsorting_samtools                                               -
[-        ] process > ampliconsorting_bgzip                                                  -
[-        ] process > ampliconsorting_fasta                                                  -
[-        ] process > ampliconsorting_lineageAssignment_Pangolin                             -
[-        ] process > ampliconsorting_lineageAssignment_Nextclade                            -
[-        ] process > report                                                                 -

ERROR ~ Error executing process > 'bammix (Looking for positions with nucleotide mixtures using bammix)'

Caused by:
  Process `bammix (Looking for positions with nucleotide mixtures using bammix)` terminated with an error exit status (1)

Command executed:

  bammix.py nextclade.tsv Samples/

Command exit status:
  1

Command output:
  0    G210T,C241T,G569A,C679T,C1387T,C1968T,C2325T,A...
  1    C241T,T670G,C3037T,C6730T,T11418C,C12459T,T129...
  2    C241T,T670G,C2790T,C3037T,G4184A,C4321T,G7452A...
  Name: substitutions, dtype: object
  0                                     1-50,29828-29903
  1    1-50,210,2790,4184,4321,5301,6196,9344,9866,98...
  2                           1-50,7123-7403,29828-29903
  Name: missing, dtype: object
  ['22786', '569', '26058', '12946', '19473', '4184', '22995', '23403', '22992', '27739', '21636', '12880', '13072', '21618', '23525', '22917', '11418', '22813', '27384', '19955', '3037', '23765', '26577', '1968', '25584', '28461', '12459', '10029', '25398', '23040', '22882', '23063', '23948', '22688', '11575', '27807', '29742', '4763', '26709', '2444', '25486', '18868', '27638', '12068', '27382', '24410', '23055', '9344', '8991', '28311', '17410', '23013', '20055', '18813', '25502', '11514', '29402', '210', '16193', '13019', '5184', '10198', '21987', '15451', '28883', '241', '23599', '24424', '18163', '670', '2790', '23075', '9424', '23854', '27259', '24469', '26060', '9534', '22578', '22686', '4321', '25810', '22197', '16466', '21846', '1387', '28881', '10447', '22227', '29510', '28271', '15714', '22775', '23014', '4207', '25855', '27131', '9042', '10449', '27752', '26858', '14457', '27383', '28882', '9891', '679', '21855', '9866', '22674', '6730', '14117', '2325', '22200', '26767', '5584', '25000', '23604', '22679', '25469', '26270', '7452', '14408']
  ['22786', '28461', '9866', '29402', '4321', '9344', '10605', '28384', '22775', '6196', '23417', '5301', '4184', '28047', '28767', '9891', '2790', '210']

Command error:
  Unable to find image 'ufuomababatunde/bammix:v1.0.0' locally
  v1.0.0: Pulling from ufuomababatunde/bammix
  f797264dfe1f: Already exists
  8397fcdbd304: Already exists
  1eeaccec0903: Already exists
  a095af5da9dc: Already exists
  789273239750: Pulling fs layer
  ec5d2936323b: Pulling fs layer
  ec5d2936323b: Waiting
  ec5d2936323b: Verifying Checksum
  ec5d2936323b: Download complete
  789273239750: Verifying Checksum
  789273239750: Download complete
  789273239750: Pull complete
  ec5d2936323b: Pull complete
  Digest: sha256:9a170248a362b2a7baba45eef10fa23cb56e92b6eaa848031b3d6ec8bef30fa4
  Status: Downloaded newer image for ufuomababatunde/bammix:v1.0.0
  find: ‘Samples/’: No such file or directory
  0    G210T,C241T,G569A,C679T,C1387T,C1968T,C2325T,A...
  1    C241T,T670G,C3037T,C6730T,T11418C,C12459T,T129...
  2    C241T,T670G,C2790T,C3037T,G4184A,C4321T,G7452A...
  Name: substitutions, dtype: object
  0                                     1-50,29828-29903
  1    1-50,210,2790,4184,4321,5301,6196,9344,9866,98...
  2                           1-50,7123-7403,29828-29903
  Name: missing, dtype: object
  ['22786', '569', '26058', '12946', '19473', '4184', '22995', '23403', '22992', '27739', '21636', '12880', '13072', '21executor >  local (16)
[4a/013296] process > concat (Concatenating fasta files into all_sequences.fasta)            [100%] 1 of 1, cached: 1 ✔
[-        ] process > pangolin (Lineage assignment using pangolin tool)                      -
[58/f0accd] process > nextclade (Lineage assignment using nextclade)                         [100%] 1 of 1 ✔
[-        ] process > lineage_assignment                                                     -
[45/9ddeba] process > bammix (Looking for positions with nucleotide mixtures using bammix)   [100%] 1 of 1, failed: 1
[-        ] process > bam_filter                                                             -
[82/9fb2c5] process > virstrain (Identifying lineage assignment for barcode07 using Virst... [100%] 3 of 3 ✔
[72/81d6a3] process > freyja (Identifying relative lineage abundances of samples to see p... [100%] 3 of 3 ✔
[26/8cbcae] process > freyja_demix (Identifying relative lineage abundances of sample bar... [100%] 3 of 3 ✔
[33/f168f1] process > freyja_aggregate (Aggregating Freyja demix results)                    [100%] 1 of 1 ✔
[0b/4921f0] process > freyja_plot (Plotting relative lineage abundances of samples)          [100%] 1 of 1 ✔
[-        ] process > makevcf                                                                -
[-        ] process > bammixplot                                                             -
[-        ] process > aafplot_mutations                                                      -
[-        ] process > aafplot_amplicons                                                      -
[-        ] process > ampliconsorting_DeltaReads                                             -
[-        ] process > ampliconsorting_OmicronReads                                           -
[-        ] process > ampliconsorting_samtools                                               -
[-        ] process > ampliconsorting_bgzip                                                  -
[-        ] process > ampliconsorting_fasta                                                  -
[-        ] process > ampliconsorting_lineageAssignment_Pangolin                             -
[-        ] process > ampliconsorting_lineageAssignment_Nextclade                            -
[-        ] process > report                                                                 -
ERROR ~ Error executing process > 'bammix (Looking for positions with nucleotide mixtures using bammix)'

Caused by:
  Process `bammix (Looking for positions with nucleotide mixtures using bammix)` terminated with an error exit status (1)

Command executed:

  bammix.py nextclade.tsv Samples/

Command exit status:
  1

Command output:
  0    G210T,C241T,G569A,C679T,C1387T,C1968T,C2325T,A...
  1    C241T,T670G,C3037T,C6730T,T11418C,C12459T,T129...
  2    C241T,T670G,C2790T,C3037T,G4184A,C4321T,G7452A...
  Name: substitutions, dtype: object
  0                                     1-50,29828-29903
  1    1-50,210,2790,4184,4321,5301,6196,9344,9866,98...
  2                           1-50,7123-7403,29828-29903
  Name: missing, dtype: object
  ['22786', '569', '26058', '12946', '19473', '4184', '22995', '23403', '22992', '27739', '21636', '12880', '13072', '21618', '23525', '22917', '11418', '22813', '27384', '19955', '3037', '23765', '26577', '1968', '25584', '28461', '12459', '10029', '25398', '23040', '22882', '23063', '23948', '22688', '11575', '27807', '29742', '4763', '26709', '2444', '25486', '18868', '27638', '12068', '27382', '24410', '23055', '9344', '8991', '28311', '17410', '23013', '20055', '18813', '25502', '11514', '29402', '210', '16193', '13019', '5184', '10198', '21987', '15451', '28883', '241', '23599', '24424', '18163', '670', '2790', '23075', '9424', '23854', '27259', '24469', '26060', '9534', '22578', '22686', '4321', '25810', '22197', '16466', '21846', '1387', '28881', '10447', '22227', '29510', '28271', '15714', '22775', '23014', '4207', '25855', '27131', '9042', '10449', '27752', '26858', '14457', '27383', '28882', '9891', '679', '21855', '9866', '22674', '6730', '14117', '2325', '22200', '26767', '5584', '25000', '23604', '22679', '25469', '26270', '7452', '14408']
  ['22786', '28461', '9866', '29402', '4321', '9344', '10605', '28384', '22775', '6196', '23417', '5301', '4184', '28047', '28767', '9891', '2790', '210']

Command error:
  Unable to find image 'ufuomababatunde/bammix:v1.0.0' locally
  v1.0.0: Pulling from ufuomababatunde/bammix
  f797264dfe1f: Already exists
  8397fcdbd304: Already exists
  1eeaccec0903: Already exists
  a095af5da9dc: Already exists
  789273239750: Pulling fs layer
  ec5d2936323b: Pulling fs layer
  ec5d2936323b: Waiting
  ec5d2936323b: Verifying Checksum
  ec5d2936323b: Download complete
  789273239750: Verifying Checksum
  789273239750: Download complete
  789273239750: Pull complete
  ec5d2936323b: Pull complete
  Digest: sha256:9a170248a362b2a7baba45eef10fa23cb56e92b6eaa848031b3d6ec8bef30fa4
  Status: Downloaded newer image for ufuomababatunde/bammix:v1.0.0
  find: ‘Samples/’: No such file or directory
  0    G210T,C241T,G569A,C679T,C1387T,C1968T,C2325T,A...
  1    C241T,T670G,C3037T,C6730T,T11418C,C12459T,T129...
  2    C241T,T670G,C2790T,C3037T,G4184A,C4321T,G7452A...
  Name: substitutions, dtype: object
  0                                     1-50,29828-29903
  1    1-50,210,2790,4184,4321,5301,6196,9344,9866,98...
  2                           1-50,7123-7403,29828-29903
  Name: missing, dtype: object
  ['22786', '569', '26058', '12946', '19473', '4184', '22995', '23403', '22992', '27739', '21636', '12880', '13072', '21618', '23525', '22917', '11418', '22813', '27384', '19955', '3037', '23765', '26577', '1968', '25584', '28461', '12459', '10029', '25398', '23040', '22882', '23063', '23948', '22688', '11575', '27807', '29742', '4763', '26709', '2444', '25486', '18868', '27638', '12068', '27382', '24410', '23055', '9344', '8991', '28311', '17410', '23013', '20055', '18813', '25502', '11514', '29402', '210', '16193', '13019', '5184', '10198', '21987', '15451', '28883', '241', '23599', '24424', '18163', '670', '2790', '23075', '9424', '23854', '27259', '24469', '26060', '9534', '22578', '22686', '4321', '25810', '22197', '16466', '21846', '1387', '28881', '10447', '22227', '29510', '28271', '15714', '22775', '23014', '4207', '25855', '27131', '9042', '10449', '27752', '26858', '14457', '27383', '28882', '9891', '679', '21855', '9866', '22674', '6730', '14117', '2325', '22200', '26767', '5584', '25000', '23604', '22679', '25469', '26270', '7452', '14408']
  ['22786', '28461', '9866', '29402', '4321', '9344', '10605', '28384', '22775', '6196', '23417', '5301', '4184', '28047', '28767', '9891', '2790', '210']
  Traceback (most recent call last):
    File "/mnt/d/dev/coinfection/CoPi/bin/bammix.py", line 72, in <module>
      bam_files = sp.check_output(
                  ^^^^^^^^^^^^^^^^
    File "/usr/lib/python3.11/subprocess.py", line 466, in check_output
      return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/lib/python3.11/subprocess.py", line 571, in run
      raise CalledProcessError(retcode, process.args,
  subprocess.CalledProcessError: Command 'find Samples/ -name "*.bam" -type f' returned non-zero exit status 1.

Work dir:
  /mnt/d/dev/coinfection/work/02/c570f33957f0474d2b30ea10728b51

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`

 -- Check '.nextflow.log' file for details
```

**Comment by lanadelrea** [comment]
I applied this fix and the scripts work for relative path as input now. Thank you so much!
