### ISSUE TITLE
Missing primer scheme files

### ISSUE THREAD

**Issue by abulenciamiguel** [lanadelrea/Katmon#8]
I assume these are similar to the missing files: [here](https://github.com/artic-network/primer-schemes/tree/master/nCoV-2019/V4.1).
I just added the following headers:
chrom, Start, End, Amplicon_ID, primerPool, strand
```
[4a/013296] process > concat (Concatenating fasta files into all_sequences.fasta)            [100%] 1 of 1, cached: 1 ✔
[fd/bcffff] process > pangolin (Lineage assignment using pangolin tool)                      [100%] 1 of 1, cached: 1 ✔
[58/f0accd] process > nextclade (Lineage assignment using nextclade)                         [100%] 1 of 1, cached: 1 ✔
[be/63e9f5] process > lineage_assignment (Create summary table for lineage assignment)       [100%] 1 of 1 ✔
[bf/a0fc5a] process > bammix (Looking for positions with nucleotide mixtures using bammix)   [100%] 3 of 3 ✔
[00/3ea58a] process > bam_filter (Getting positions flagged by bammix)                       [100%] 3 of 3 ✔
[49/398c80] process > virstrain (Identifying lineage assignment for barcode07 using Virst... [100%] 3 of 3 ✔
[72/81d6a3] process > freyja (Identifying relative lineage abundances of samples to see p... [100%] 3 of 3, cached: 3 ✔
[26/8cbcae] process > freyja_demix (Identifying relative lineage abundances of sample bar... [100%] 3 of 3, cached: 3 ✔
[33/f168f1] process > freyja_aggregate (Aggregating Freyja demix results)                    [100%] 1 of 1, cached: 1 ✔
[0b/4921f0] process > freyja_plot (Plotting relative lineage abundances of samples)          [100%] 1 of 1, cached: 1 ✔
[4a/428092] process > makevcf (Making vcf file of high quality reads from bam file of bar... [100%] 3 of 3 ✔
[04/4fe4c6] process > bammixplot (Plotting bammix plot for barcode09)                        [100%] 1 of 1 ✔
[4d/7df3d3] process > aafplot_mutations (Plotting alternative allele fraction per mutatio... [100%] 1 of 1 ✔
[03/d868e7] process > aafplot_amplicons (Plotting alternative allele fraction per mutatio... [100%] 1 of 1, failed: 1 ✘
[d6/f7cffb] process > ampliconsorting_DeltaReads (Sorting Delta reads of barcode09 suspec... [100%] 1 of 1 ✔
[91/75ce11] process > ampliconsorting_OmicronReads (Sorting Omicron reads of barcode09 su... [100%] 1 of 1 ✔
[-        ] process > ampliconsorting_samtools (Creating vcf from Delta and Omicron sorte... -
[-        ] process > ampliconsorting_bgzip                                                  -
[-        ] process > ampliconsorting_fasta                                                  -
[-        ] process > ampliconsorting_lineageAssignment_Pangolin                             -
[-        ] process > ampliconsorting_lineageAssignment_Nextclade                            -
[-        ] process > report                                                                 -

ERROR ~ Error executing process > 'aafplot_amplicons (Plotting alternative allele fraction per mutation of barcode09)'

Caused by:
  Process `aafplot_amplicons (Plotting alternative allele fraction per mutation of barcode09)` terminated with an error exit status (1)

Command executed:

  aafplot_amplicon.py /mnt/d/dev/coinfection/CoPi/assets/primer-schemes/nCoV-2019/V4.1/SARS-CoV-2.scheme.bed     barcode09_read_depth.tsv     barcode09     barcode09_AAFplot_amplicons.png

Command exit status:
  1

Command output:
  (empty)

Command error:
  Traceback (most recent call last):
    File "/mnt/d/dev/coinfection/CoPi/bin/aafplot_amplicon.py", line 18, in <module>
      primer_scheme = pd.read_csv(primer_scheme_file, sep='\t')
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 912, in read_csv
      return _read(filepath_or_buffer, kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 577, in _read
      parser = TextFileReader(filepath_or_buffer, **kwds)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1407, in __init__
      self._engine = self._make_engine(f, self.engine)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1661, in _make_engine
      self.handles = get_handle(
                     ^^^^^^^^^^^
    File "/usr/lib/python3.11/site-packages/pandas/io/common.py", line 859, in get_handle
      handle = open(
               ^^^^^
  FileNotFoundError: [Errno 2] No such file or directory: '/mnt/d/dev/coinfection/CoPi/assets/primer-schemes/nCoV-2019/V4.1/SARS-CoV-2.scheme.bed'

Work dir:
  /mnt/d/dev/coinfection/work/03/d868e766dd08c929fb756048c354e5

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`

 -- Check '.nextflow.log' file for details
 ```

**Comment by lanadelrea** [comment]
Fixed this by removing then copying, then pushing the folder containing the primer schemes. Thank you sir!
